### ISSUE TITLE
FMX energy scan issues

### ISSUE THREAD

**Issue by JunAishima** [NSLS-II/lsdc#119]
Reported in spreadsheet - this appears in the log from an hour ago:

2021-09-13 14:36:32,411 daq_lib  INFO     robot gov status = False
2021-09-13 14:36:33,412 daq_lib  INFO     robot gov state = 1
**2021-09-13 14:36:33,577 daq_main_common ERROR    Attribute Error: 'list' object has no attribute 'sum'**
2021-09-13 15:29:41,637 daq_main_common INFO     command: openPort(1)
2021-09-13 15:29:41,648 daq_lib  INFO     Mon Sep 13 15:29:41 2021
openPort(1)
2021-09-13 15:29:41,648 daq_main_common INFO     executing command: openPort(1)
2021-09-13 15:30:58,311 daq_main_common INFO     command: closePorts()

**Comment by JunAishima** [comment]
the field 'mercury_mca_spectrum' now returns a list, which apparently can't be summed.

Was Bluesky returning a different type that could be summed before?
lsdcServer_2021-1.0 - bluesky 1.6.0rc4, ophyd 1.4.0rc5
lsdc-server-2021-1.1 - bluesky 1.7.0, ophyd 1.6.2

**Comment by RobertSchaffer1** [comment]
I admit I'm a little lost - nowhere in daq_main_common.py does it attempt to sum anything, unless I'm missing something. Has this error occurred somewhere downstream and just not outputted any of the useful traceback information? If so, is there a place to go to get it?

**Comment by RobertSchaffer1** [comment]
Tbh, now I'm even more lost - why did the error log say:

2021-09-13 14:36:33,577 daq_main_common ERROR Attribute Error: 'list' object has no attribute 'sum'

if the error occurred in daq_macros and not daq_main_common? How did you find the error if there is no traceback info?

In any case, you can sum a list of numbers, just use the sum() command on it instead of calling its sum attribute. Should be a pretty quick fix.

WRT the plotting, it looks like a separate (much more serious) issue, will take some time to try to understand.

**Comment by JunAishima** [comment]
Data coming out of LSDC before:

**Comment by JunAishima** [comment]
Looks like that simple fix (doing sum correctly) made the scan work. so nothing to do with bluesky and ophyd.

There is an exception at the end for "chooch not found" - so there may be an issue with setting up environment and from what Martin was just saying, CCP4.

**Comment by JunAishima** [comment]
downstream issue of broken chooch partly fixed by correcting PATH (also putting ccp4 at place indicated in PATH): https://github.com/NSLS-II/lsdc/commit/7659e2f4e4f68e14f7879825036d710726597bde
